### ISSUE TITLE
field_name_conditions is unknown/unexpected

### ISSUE THREAD

**Issue by jabrcks** [SigmaHQ/pySigma-pipeline-crowdstrike#4]
Hi, I am getting the following error message when converting with pysigma 0.8.9:
TypeError: __init__() got an unexpected keyword argument \'field_name_conditions\'

Has anyone observed similar behaviour? I scrolled over pysigma source code and there you should have the possibility to use this conditions - I am using the newst version of this repository.

**Comment by thomaspatzke** [comment]
Appears a bug to me, investigating it! Must be introduced somewhere after pySigma 0.8.1, the version used as dependency in this repo where tests pass.

**Comment by thomaspatzke** [comment]
Tested it locally and also on GitHub Actions, can't reproduce it.

In [this run](https://github.com/SigmaHQ/pySigma-pipeline-crowdstrike/actions/runs/3569309877/jobs/5999135091) it runs [with pySigma 0.8.9](https://github.com/SigmaHQ/pySigma-pipeline-crowdstrike/actions/runs/3569309877/jobs/5999135091#step:5:37) and the tests pass.

Can you please check your environment? The error is expected when the current version of the CrowdStrike pipeline runs with pySigma<0.8.
